##########################
## Spring configuration ##
##########################
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user/**
        - id: event
          uri: lb://EVENT
          predicates:
            - Path=/api/event/**
        - id: registration-dashboards
          uri: lb://REGISTRATION-DASHBOARD
          predicates:
            - Path=/api/registration-dashboard/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS

server:
  port: 8080

###################
## Naming Server ##
###################
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

